sudo: false
language: python
python:
  - 2.7
git:
  submodules: false
addons:
  postgresql: 9.6
install:
  - pip install -U pip setuptools
  - pip install isort
  - pip install -e .
script:
  - isort -rc --diff --check-only indico/
  - python bin/maintenance/update_backrefs.py --ci
  - pytest
notifications:
  email: false
  irc:
    channels:
      - 'chat.freenode.net#indico'
    use_notice: true
    skip_join: true
